### ISSUE TITLE
Let user upload a pdf file and receive data from this file

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/bubble_scan#12]
**Description**
One of the fundamental functionalities of this application is allowing user to upload a digital copy of the scantron sheet and to get the data contained in that sheet: student's id and student's answers for each question. This means that the necessary pieces need to be added to the client and server side applications, and these pieces need to be integrated together. While we currently don't have the necessary AI component for extracting the data from the scantron sheet, we can build the software infrastructure capable of passing the file from the client to the server, and calling the AI module (the mock AI module for now). 

**Describe the solution you'd like**
At this stage, I'd like a simple solution as follows:
1. The user can upload a the inputData/exampleScans.pdf file through the user interface.
1. The user gets a response with the following data per exam: student id, question 1 answer, question 2 answer, ..., question 50 answer
1. The data is displayed in simple format in the user interface (nothing fancy, the simplest way is best at this point)

**Additional Context**
This is a container issue, which is further broken into smaller issues listed below:

**Comment by rkarmuri** [comment]
We built the software infrastructure capable of passing the file from the client to the server and calling the AI module. The user can upload the inputData/exampleScans.pdf file through the user interface successfully. The user gets a response with the following data per exam student ID, question 1 answer, question 2 answer, ..., question 50 answer successfully. The data is displayed in a CSV format as required by the client. Hence, the issue is resolved and closed.
